version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: duacode_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: duacode_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - duacode_network

volumes:
  db_data:

networks:
  duacode_network:
    driver: bridge
